### ISSUE TITLE
GmsCompat app not present in manifest

### ISSUE THREAD

**Issue by PeterCxy** [ProtonAOSP/android_manifest#14]
The updated GmsCompat code needs the companion app but it is not present in the manifest, causing problems with custom builds.

**Comment by AnonymousProxy987** [comment]
Is GmsCompat even used in ProtonAOSP?

GmsCompat seems to already be included in `PRODUCT_PACKAGES`, so all I had to do was clone GmsCompat to `packages/apps` before compiling a build with `WITH_GMS=true`. Simply doing this is enough to get the "Sandboxed Google Play" option to appear under Settings > Apps.

However, clicking this option immediately opens the information article on GrapheneOS' website. The settings cannot be used.

[This commit by kdrag0n](https://github.com/ProtonAOSP/android_packages_apps_GmsCompat/commit/c37bb3ac788258cf4c866e79366cabc910499df9) suggests that GmsCompat isn't being used, and that my compiled ROM is using full privileged Google Play Services, not the sandboxed version, since it fails that check on line 18.

Maybe GmsCompat's exclusion from the manifest was therefore intentional?

In any case, I would like to know how to properly compile ProtonAOSP with sandboxed Google Play Services instead of the full privileged services. All I did for my build was simply build it with `WITH_GMS=true`. Are more steps required? Hopefully kdrag0n can clarify.

**Comment by PeterCxy** [comment]
@AnonymousProxy987 If you want sandbox GMS, **do not** build with `WITH_GMS=true`. Simply build with the default options and install GMS from GrapheneOS repository.

GmsCompat **is** being used if you don't set `WITH_GMS=true`.

**Comment by AnonymousProxy987** [comment]
Ah, I see. I misunderstood what that option was doing when reading the build documentation. I thought that option was required to include the rest of the Google apps (some of which need to be system apps in order to function), not to allow full privileged GMS along with it.

I guess having those system apps or Sandboxed Google Play is mutually exclusive?
